1. StringIO
2. Pandas read_csv

In [1]:
## Reading different data source with help of pandas
from io import StringIO   # StringIO help to read csv file
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\sushi\Downloads/dataset.csv")
df.head()

,EmployeeID,Name,Department,Age,Gender,Salary,ExperienceYears,City,JoiningYear
0,101,Amit,IT,25,M,40000,2,Delhi,2022
1,102,Suresh,HR,30,M,35000,5,Mumbai,2019
2,103,Ravi,IT,28,M,45000,3,Delhi,2021
3,104,Neha,Finance,35,F,60000,10,Pune,2015
4,105,Pooja,HR,26,F,38000,4,Mumbai,2020

In [36]:
StringIO(df)   # this is data Frame not string

TypeError: initial_value must be str or None, not DataFrame

In [18]:
data = ('col1,col2,col3\n'     # This is str type data that work in csv file
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3\n'
       'p,q,4')
type(data)

str

In [12]:
# In memory file format object
StringIO(data)

In [19]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3
3    p    q     4

In [23]:
pd.read_csv(StringIO(data),usecols=['col1', 'col2', 'col3'])

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3
3    p    q     4

In [28]:
df.to_csv(r"C:\Users\sushi\Downloads/dataset.csv",index = False)  # index method remove the index in file

In [29]:
pd.read_csv(r"C:\Users\sushi\Downloads/dataset.csv")

,EmployeeID,Name,Department,Age,Gender,Salary,ExperienceYears,City,JoiningYear
0,101,Amit,IT,25,M,40000,2,Delhi,2022
1,102,Suresh,HR,30,M,35000,5,Mumbai,2019
2,103,Ravi,IT,28,M,45000,3,Delhi,2021
3,104,Neha,Finance,35,F,60000,10,Pune,2015
4,105,Pooja,HR,26,F,38000,4,Mumbai,2020
5,106,Ankit,IT,29,M,50000,6,Bangalore,2018
6,107,Rahul,Marketing,32,M,42000,7,Delhi,2017
7,108,Kiran,Finance,40,M,70000,15,Pune,2010
8,109,Sneha,Marketing,27,F,39000,3,Bangalore,2021
9,110,Vikas,IT,31,M,52000,8,Mumbai,2016

In [44]:
data = ('col1,col2,col3\n'     # This is str type data that work in csv file
        'x,y,1\n'
        'a,b,2\n'
        'c,d\n'
       'p')

In [45]:
pd.read_csv(StringIO(data))  # select nan value by default

  col1 col2  col3
0    x    y   1.0
1    a    b   2.0
2    c    d   NaN
3    p  NaN   NaN

In [35]:
df = pd.read_csv(StringIO(data),dtype = 'object')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      object
 1   col2    3 non-null      object
 2   col3    3 non-null      object
dtypes: object(3)
memory usage: 228.0+ bytes

In [49]:
data1 = ('a,b,c,d\n'
        '2,3,4,5\n'
        '1.2,3.4,4\n'
        '5,6,7')
type(data1)
pd.read_csv(StringIO(data1))

     a    b  c    d
0  2.0  3.0  4  5.0
1  1.2  3.4  4  NaN
2  5.0  6.0  7  NaN

In [51]:
df = pd.read_csv(StringIO(data),dtype = {'a':int,'b':float,'c':int})

In [53]:
df.info() 
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      object
 1   col2    3 non-null      object
 2   col3    2 non-null      float64
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

col1     object
col2     object
col3    float64
dtype: object

In [55]:
data = ('index,a,b,c\n'
        '2,apple,mango,4.56\n'
        '4,grapes,guava,5.78')
pd.read_csv(StringIO(data))

   index       a      b     c
0      2   apple  mango  4.56
1      4  grapes  guava  5.78

In [60]:
pd.read_csv(StringIO(data),usecols= ['a','b','c'],index_col=0)

            b     c
a
apple   mango  4.56
grapes  guava  5.78

In [ ]:
pd.read_csv('url')  # you can read any url data with help of csv reader