In [1]:
import pandas as pd

In [2]:
dic = {'Name':['Sushil','Himanshu','Honey'],
      'Age':[21,18,24],
      'City':['Aligarh','Aligarh']}

In [3]:
df = pd.DataFrame([dic])

In [4]:
df

                        Name           Age                City
0  [Sushil, Himanshu, Honey]  [21, 18, 24]  [Aligarh, Aligarh]

In [35]:
df = pd.DataFrame({'Name':['Sushil','Himanshu','Honey'],
      'Age':[21,18,24],
      'City':['Aligarh','Aligarh','Gaziabad']})

In [36]:
df

       Name  Age      City
0    Sushil   21   Aligarh
1  Himanshu   18   Aligarh
2     Honey   24  Gaziabad

In [37]:
df = pd.read_csv('netflix_titles.csv')

In [38]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [40]:
# To see Basic Info Of DataSet
df.shape

(8807, 12)

In [43]:
df.head()['title']

0     Dick Johnson Is Dead
1            Blood & Water
2                Ganglands
3    Jailbirds New Orleans
4             Kota Factory
Name: title, dtype: object

In [47]:
cast_col = df.head()['cast']
type(cast_col)

pandas.core.series.Series

In [56]:
# columns = (df['title'],df['director'])
df2 = pd.DataFrame({df['title'],df['director']})
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,8797,8798,8799,8800,8801,8802,8803,8804,8805,8806
title,Dick Johnson Is Dead,Blood & Water,Ganglands,Jailbirds New Orleans,Kota Factory,Midnight Mass,My Little Pony: A New Generation,Sankofa,The Great British Baking Show,The Starling,...,Zak Storm,Zed Plus,Zenda,Zindagi Gulzar Hai,Zinzana,Zodiac,Zombie Dumb,Zombieland,Zoom,Zubaan
director,Kirsten Johnson,NaN,Julien Leclercq,NaN,NaN,Mike Flanagan,"Robert Cullen, José Luis Ucha",Haile Gerima,Andy Devonshire,Theodore Melfi,...,NaN,Chandra Prakash Dwivedi,Avadhoot Gupte,NaN,Majid Al Ansari,David Fincher,NaN,Ruben Fleischer,Peter Hewitt,Mozez Singh

In [59]:
df.head()['release_year']>2020

0    False
1     True
2     True
3     True
4     True
Name: release_year, dtype: bool

In [5]:
df1 = pd.read_csv('homeprices.csv')
df1

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
df1['place'] = ['rular', 'town','village','city','town','city']

In [7]:
df1['area'] = [2600,3000,3200,3600,4000,4100]

In [8]:
df1

   area  bedrooms  age   price    place
0  2600       3.0   20  550000    rular
1  3000       4.0   15  565000     town
2  3200       NaN   18  610000  village
3  3600       3.0   30  595000     city
4  4000       5.0    8  760000     town
5  4100       6.0    8  810000     city

In [9]:
df1.drop('place', axis=1)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
df1.rename(columns={'area': 'Area'}, inplace=True)

In [11]:
df1

   Area  bedrooms  age   price    place
0  2600       3.0   20  550000    rular
1  3000       4.0   15  565000     town
2  3200       NaN   18  610000  village
3  3600       3.0   30  595000     city
4  4000       5.0    8  760000     town
5  4100       6.0    8  810000     city

In [12]:
empty_val = df1['bedrooms'].isnull().sum()
# empty_val

np.int64(1)

In [17]:
#Fill Missing values

mean_val = df1['bedrooms'].mean()
mean_val

np.float64(3.5)

In [20]:
df1['bedrooms'] = df1['bedrooms'].fillna(mean_val)

In [21]:
df1

   Area  bedrooms  age   price    place
0  2600       3.0   20  550000    rular
1  3000       4.0   15  565000     town
2  3200       0.0   18  610000  village
3  3600       3.0   30  595000     city
4  4000       5.0    8  760000     town
5  4100       6.0    8  810000     city

In [22]:
#Drop Missing Rows
df2 = pd.read_csv('homeprices.csv')
df2

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [36]:
is_null = df2['bedrooms'].isnull()
df2

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [48]:
df2.drop(df2[df2['bedrooms'].isnull()].index, axis=0, inplace=True)

In [49]:
df2[df2['bedrooms'].isnull()].index

Index([], dtype='int64')

In [50]:
df2

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [61]:
#Sorting (Ascending and Descending)
new_df2 = df2.sort_values('area', ascending=True)

In [62]:
new_df2

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [60]:
df2.sort_values('price', ascending=False)

   area  bedrooms  age   price
5  4100       6.0    8  810000
4  4000       5.0    8  760000
3  3600       3.0   30  595000
1  3000       4.0   15  565000
0  2600       3.0   20  550000

In [70]:
# Count the Columns Data
# ind = df2[df2['price'].notnull()].index

df2.count()

area        5
bedrooms    5
age         5
price       5
dtype: int64

In [90]:
# Apply Function  add some numbers in table data

def add_nums(n):
    new_df = df2['price']+n
    return new_df

In [91]:
add_nums(100)

0    550100
1    565100
3    595100
4    760100
5    810100
Name: price, dtype: int64

In [95]:
# GroupBy
# Department ke basis par average salary nikaalo.  (Find Mean)

av_sal = df2['price'].mean()

In [96]:
print('Average Price: ',av_sal)

Average Price:  656000.0

In [102]:
# Merge DataFrames 
#  Merge Two DataFrame in one Frame
df1 = pd.read_csv('homeprices1.csv')

In [103]:
df2 = pd.read_csv('hiring.csv')

In [104]:
pd.merge(df1,df2, on='index')            # For Merge th

   area   price  index experience  interview_score(out of 10)  salary($)
0  2600  550000      1       four                           9      50000
1  3000  565000      2      eight                           6      45000
2  3200  610000      3       five                           7      60000
3  3600  680000      4        two                          10      65000
4  4000  725000      5      seven                           6      70000

In [ ]:
# Concatenate ->
# Do DataFrames ko vertically ya horizontally join karo.