In [1]:
import pandas as pd

In [21]:
df = pd.read_excel('weather_data_20days.xlsx')

In [30]:
df.head()

,date_ist,time_ist,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,condition_text,description,aqi_index,pm2_5,pm10,co,no2
0,2025-01-01,00:00:00,Anand Vihar,28.6469,77.316,8.1,100,995.4,2.9,Mainly clear,WMO Code 1,197,185.8,188.6,1907,56.7
1,2025-01-01,01:00:00,Anand Vihar,28.6469,77.316,7.7,100,994.7,3.2,Overcast,WMO Code 3,198,174.6,177.4,1669,44.8
2,2025-01-01,02:00:00,Anand Vihar,28.6469,77.316,7.5,100,994.3,4.5,Overcast,WMO Code 3,199,164.4,166.7,1493,34.7
3,2025-01-01,03:00:00,Anand Vihar,28.6469,77.316,7.8,99,994.1,6.0,Overcast,WMO Code 3,200,156.5,158.8,1401,26.7
4,2025-01-01,04:00:00,Anand Vihar,28.6469,77.316,7.3,100,993.8,6.8,Overcast,WMO Code 3,200,149.5,151.8,1372,20.6

In [31]:
df['location']

0     Anand Vihar
1     Anand Vihar
2     Anand Vihar
3     Anand Vihar
4     Anand Vihar
5     Anand Vihar
6     Anand Vihar
7     Anand Vihar
8     Anand Vihar
9     Anand Vihar
10    Anand Vihar
11    Anand Vihar
12    Anand Vihar
13    Anand Vihar
14    Anand Vihar
15    Anand Vihar
16    Anand Vihar
17    Anand Vihar
18    Anand Vihar
Name: location, dtype: object

In [35]:
df['temp_c'].max()

In [37]:
df.describe()

,date_ist,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,aqi_index,pm2_5,pm10,co,no2
count,19,1.900000e+01,1.900000e+01,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,11.142105,89.157895,994.310526,5.794737,200.210526,138.600000,141.184211,1467.947368,29.863158
min,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,7.300000,70.000000,992.200000,2.800000,197.000000,99.400000,102.700000,1037.000000,13.100000
25%,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,7.900000,78.500000,993.650000,4.600000,200.000000,119.000000,121.800000,1314.500000,20.550000
50%,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,9.400000,97.000000,994.300000,6.200000,200.000000,141.100000,143.000000,1486.000000,26.700000
75%,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,14.750000,99.000000,995.300000,6.850000,201.000000,156.500000,158.550000,1649.000000,34.000000
max,2025-01-01 00:00:00,2.864690e+01,7.731600e+01,16.900000,100.000000,996.300000,8.800000,202.000000,185.800000,188.600000,1910.000000,56.700000
std,NaN,3.650066e-15,1.460027e-14,3.695691,11.861531,1.330370,1.765872,1.228321,25.197861,25.075248,267.076867,13.597108

In [43]:
df[df.temp_c==14.6]

,date_ist,time_ist,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,condition_text,description,aqi_index,pm2_5,pm10,co,no2
12,2025-01-01,12:00:00,Anand Vihar,28.6469,77.316,14.6,77,994.7,6.3,Clear sky,WMO Code 0,200,115.5,118.3,1079,15.4

In [47]:
df[df.temp_c==df['temp_c'].max()]

,date_ist,time_ist,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,condition_text,description,aqi_index,pm2_5,pm10,co,no2
15,2025-01-01,15:00:00,Anand Vihar,28.6469,77.316,16.9,70,992.3,6.9,Clear sky,WMO Code 0,201,99.4,102.7,1291,21.0

In [49]:
df[['date_ist','temp_c','location']][df.temp_c == df['temp_c'].max()]

     date_ist  temp_c     location
15 2025-01-01    16.9  Anand Vihar

In [56]:
df.set_index('date_ist', inplace=True)

In [57]:
df.loc['2025-01-01']

,time_ist,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,condition_text,description,aqi_index,pm2_5,pm10,co,no2
date_ist,,,,,,,,,,,,,,,
2025-01-01,00:00:00,Anand Vihar,28.6469,77.316,8.1,100,995.4,2.9,Mainly clear,WMO Code 1,197,185.8,188.6,1907,56.7
2025-01-01,01:00:00,Anand Vihar,28.6469,77.316,7.7,100,994.7,3.2,Overcast,WMO Code 3,198,174.6,177.4,1669,44.8
2025-01-01,02:00:00,Anand Vihar,28.6469,77.316,7.5,100,994.3,4.5,Overcast,WMO Code 3,199,164.4,166.7,1493,34.7
2025-01-01,03:00:00,Anand Vihar,28.6469,77.316,7.8,99,994.1,6.0,Overcast,WMO Code 3,200,156.5,158.8,1401,26.7
2025-01-01,04:00:00,Anand Vihar,28.6469,77.316,7.3,100,993.8,6.8,Overcast,WMO Code 3,200,149.5,151.8,1372,20.6
2025-01-01,05:00:00,Anand Vihar,28.6469,77.316,7.6,99,993.9,7.3,Overcast,WMO Code 3,201,156.5,158.3,1387,33.3
2025-01-01,06:00:00,Anand Vihar,28.6469,77.316,8.1,99,994.7,4.8,Overcast,WMO Code 3,201,144.4,146.2,1486,31.4
2025-01-01,07:00:00,Anand Vihar,28.6469,77.316,8.0,99,995.2,4.0,Overcast,WMO Code 3,201,138.3,140.6,1629,28.7
2025-01-01,08:00:00,Anand Vihar,28.6469,77.316,8.4,99,995.7,6.5,Overcast,WMO Code 3,200,136.4,138.8,1683,26.0
2025-01-01,09:00:00,Anand Vihar,28.6469,77.316,9.4,97,996.3,8.0,Overcast,WMO Code 3,200,141.1,143.0,1556,23.3
2025-01-01,10:00:00,Anand Vihar,28.6469,77.316,11.3,89,996.3,8.8,Overcast,WMO Code 3,200,129.9,132.2,1338,20.5
2025-01-01,11:00:00,Anand Vihar,28.6469,77.316,13.1,81,995.9,8.1,Partly cloudy,WMO Code 2,200,122.5,125.3,1169,18.2
2025-01-01,12:00:00,Anand Vihar,28.6469,77.316,14.6,77,994.7,6.3,Clear sky,WMO Code 0,200,115.5,118.3,1079,15.4
2025-01-01,13:00:00,Anand Vihar,28.6469,77.316,15.8,73,993.5,6.2,Clear sky,WMO Code 0,200,108.7,111.8,1037,13.1
2025-01-01,14:00:00,Anand Vihar,28.6469,77.316,16.5,72,992.6,6.3,Clear sky,WMO Code 0,201,103.6,106.6,1085,14.1
2025-01-01,15:00:00,Anand Vihar,28.6469,77.316,16.9,70,992.3,6.9,Clear sky,WMO Code 0,201,99.4,102.7,1291,21.0
2025-01-01,16:00:00,Anand Vihar,28.6469,77.316,16.5,72,992.2,6.0,Clear sky,WMO Code 0,201,100.4,102.9,1586,31.3
2025-01-01,17:00:00,Anand Vihar,28.6469,77.316,14.9,80,992.2,4.7,Clear sky,WMO Code 0,202,148.5,151.8,1813,52.6
2025-01-01,18:00:00,Anand Vihar,28.6469,77.316,12.2,88,994.1,2.8,Clear sky,WMO Code 0,202,157.4,160.7,1910,55.0

In [61]:
df.set_index('condition_text', inplace=True)
df

,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,description,aqi_index,pm2_5,pm10,co,no2
condition_text,,,,,,,,,,,,,
Mainly clear,Anand Vihar,28.6469,77.316,8.1,100,995.4,2.9,WMO Code 1,197,185.8,188.6,1907,56.7
Overcast,Anand Vihar,28.6469,77.316,7.7,100,994.7,3.2,WMO Code 3,198,174.6,177.4,1669,44.8
Overcast,Anand Vihar,28.6469,77.316,7.5,100,994.3,4.5,WMO Code 3,199,164.4,166.7,1493,34.7
Overcast,Anand Vihar,28.6469,77.316,7.8,99,994.1,6.0,WMO Code 3,200,156.5,158.8,1401,26.7
Overcast,Anand Vihar,28.6469,77.316,7.3,100,993.8,6.8,WMO Code 3,200,149.5,151.8,1372,20.6
Overcast,Anand Vihar,28.6469,77.316,7.6,99,993.9,7.3,WMO Code 3,201,156.5,158.3,1387,33.3
Overcast,Anand Vihar,28.6469,77.316,8.1,99,994.7,4.8,WMO Code 3,201,144.4,146.2,1486,31.4
Overcast,Anand Vihar,28.6469,77.316,8.0,99,995.2,4.0,WMO Code 3,201,138.3,140.6,1629,28.7
Overcast,Anand Vihar,28.6469,77.316,8.4,99,995.7,6.5,WMO Code 3,200,136.4,138.8,1683,26.0
Overcast,Anand Vihar,28.6469,77.316,9.4,97,996.3,8.0,WMO Code 3,200,141.1,143.0,1556,23.3
Overcast,Anand Vihar,28.6469,77.316,11.3,89,996.3,8.8,WMO Code 3,200,129.9,132.2,1338,20.5
Partly cloudy,Anand Vihar,28.6469,77.316,13.1,81,995.9,8.1,WMO Code 2,200,122.5,125.3,1169,18.2
Clear sky,Anand Vihar,28.6469,77.316,14.6,77,994.7,6.3,WMO Code 0,200,115.5,118.3,1079,15.4
Clear sky,Anand Vihar,28.6469,77.316,15.8,73,993.5,6.2,WMO Code 0,200,108.7,111.8,1037,13.1
Clear sky,Anand Vihar,28.6469,77.316,16.5,72,992.6,6.3,WMO Code 0,201,103.6,106.6,1085,14.1
Clear sky,Anand Vihar,28.6469,77.316,16.9,70,992.3,6.9,WMO Code 0,201,99.4,102.7,1291,21.0
Clear sky,Anand Vihar,28.6469,77.316,16.5,72,992.2,6.0,WMO Code 0,201,100.4,102.9,1586,31.3
Clear sky,Anand Vihar,28.6469,77.316,14.9,80,992.2,4.7,WMO Code 0,202,148.5,151.8,1813,52.6
Clear sky,Anand Vihar,28.6469,77.316,12.2,88,994.1,2.8,WMO Code 0,202,157.4,160.7,1910,55.0

In [62]:
df.loc['Clear sky']

,location,lat,lon,temp_c,humidity,pressure_mb,windspeed_kph,description,aqi_index,pm2_5,pm10,co,no2
condition_text,,,,,,,,,,,,,
Clear sky,Anand Vihar,28.6469,77.316,14.6,77,994.7,6.3,WMO Code 0,200,115.5,118.3,1079,15.4
Clear sky,Anand Vihar,28.6469,77.316,15.8,73,993.5,6.2,WMO Code 0,200,108.7,111.8,1037,13.1
Clear sky,Anand Vihar,28.6469,77.316,16.5,72,992.6,6.3,WMO Code 0,201,103.6,106.6,1085,14.1
Clear sky,Anand Vihar,28.6469,77.316,16.9,70,992.3,6.9,WMO Code 0,201,99.4,102.7,1291,21.0
Clear sky,Anand Vihar,28.6469,77.316,16.5,72,992.2,6.0,WMO Code 0,201,100.4,102.9,1586,31.3
Clear sky,Anand Vihar,28.6469,77.316,14.9,80,992.2,4.7,WMO Code 0,202,148.5,151.8,1813,52.6
Clear sky,Anand Vihar,28.6469,77.316,12.2,88,994.1,2.8,WMO Code 0,202,157.4,160.7,1910,55.0